import { useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { StyleSheet, View } from 'react-native';

import { Avatar, Button, Card, DetailHeader, IconChip, ListRow, MetricCard, ProgressBar, ScreenContainer, SectionHeading, Segmented, StatusPill, Text, TrendChart } from '@/components';
import { family, medications, providerById, pulseFor } from '@/data';
import { useAppState } from '@/state';
import { accents, colors, spacing } from '@/theme';
import type { MemberId } from '@/types';

const tabs = ['Overview', 'Health', 'Records', 'Care'] as const;

export default function MemberProfileScreen() {
  const { id = 'arjun' } = useLocalSearchParams<{ id: MemberId }>();
  const [tab, setTab] = useState<typeof tabs[number]>('Overview');
  const member = family.find((item) => item.id === id) ?? family[0]!;
  const metrics = pulseFor(member.id).metrics;
  const { records, tasks, bookings, goals } = useAppState();
  const goal = goals.find((item) => item.memberId === member.id)!;
  const memberRecords = records.filter((item) => item.memberId === member.id);
  const memberTasks = tasks.filter((item) => item.memberId === member.id && !item.completed);
  const memberBookings = bookings.filter((item) => item.memberId === member.id && item.status === 'Confirmed');
  const meds = medications.filter((item) => item.memberId === member.id);

  return <ScreenContainer edges={['top', 'bottom']}><DetailHeader title="Member profile" actionLabel="Edit" onAction={() => router.push(`/settings/profile-${member.id}`)} /><Card style={styles.profile}><Avatar name={member.name} accent={member.accent} size={70} /><View style={styles.profileCopy}><Text variant="title2">{member.name}</Text><Text variant="subhead" color={colors.textSecondary}>{member.relation} · {member.age} · {member.location}</Text><StatusPill label={member.status} accent={member.accent} /></View></Card><Text variant="caption" color={colors.textTertiary} style={styles.updated}>Last updated today, 6:42 pm</Text><Segmented options={tabs} value={tab} onChange={setTab} />
    {tab === 'Overview' ? <View style={styles.sections}><SectionHeading title="July goal" /><Card onPress={() => router.push('/goals')}><Text variant="headline">{goal.title}</Text><Text variant="footnote" color={colors.textSecondary} style={styles.gap}>{goal.caption}</Text><ProgressBar progress={goal.current / goal.target} accent={goal.accent} accessibilityLabel={goal.caption} /></Card><SectionHeading title="Health snapshot" /><View style={styles.metricRow}>{metrics.slice(0, 2).map((metric) => <MetricCard key={metric.kind} style={styles.metric} label={metric.label} value={metric.value} caption={metric.caption} pastel={metric.pastel} icon={<Feather name={metric.icon} size={18} color={colors.textPrimary} />} onPress={() => router.push(`/metric/${member.id}/${metric.kind}`)} />)}</View><MetricCard label={metrics[2]!.label} value={metrics[2]!.value} caption={metrics[2]!.caption} pastel={metrics[2]!.pastel} icon={<Feather name={metrics[2]!.icon} size={18} color={colors.textPrimary} />} onPress={() => router.push(`/metric/${member.id}/${metrics[2]!.kind}`)} /><SectionHeading title="Current context" /><Card><Info label="Conditions" value={member.conditions.length ? member.conditions.join(' · ') : 'No current conditions recorded'} /><View style={styles.line} /><Info label="Allergies" value={member.allergies.join(' · ')} /></Card><SectionHeading title="Today" /><Card padding={spacing.sm}>{memberTasks.length ? memberTasks.map((task) => <ListRow key={task.id} title={task.title} subtitle={task.time} onPress={() => router.push(`/tasks?focus=${task.id}`)} leading={<IconChip size={40} background={accents[task.accent].tint}><Feather name={task.icon} size={18} color={accents[task.accent].solid} /></IconChip>} />) : <Text variant="callout" color={colors.textSecondary} style={styles.empty}>Nothing open for today.</Text>}</Card><SectionHeading title="Next care booking" /><BookingList bookings={memberBookings} /><SectionHeading title="Recent timeline" /><Card padding={spacing.sm}><ListRow title={memberRecords[0]?.title ?? 'Profile updated'} subtitle={memberRecords[0]?.date ?? 'Today'} onPress={memberRecords[0] ? () => router.push(`/record/${memberRecords[0]!.id}`) : undefined} /><ListRow title="Health timeline organised" subtitle="This week" /></Card></View> : null}
    {tab === 'Health' ? <View style={styles.sections}><SectionHeading title="All health metrics" />{metrics.map((metric) => <Card key={metric.kind} onPress={() => router.push(`/metric/${member.id}/${metric.kind}`)}><View style={styles.metricTitle}><Text variant="headline">{metric.label}</Text><Text variant="title3">{metric.value}</Text></View><TrendChart values={metric.history.map((item) => item.value)} labels={metric.history.filter((_, i) => i === 0 || i === 3 || i === 6).map((item) => item.label)} /></Card>)}<SectionHeading title="Conditions & allergies" /><Card><Info label="Conditions" value={member.conditions.join(' · ') || 'None recorded'} /><View style={styles.line} /><Info label="Allergies" value={member.allergies.join(' · ')} /></Card><SectionHeading title="Medication adherence" /><Card><Text variant="title2">{metrics.find((metric) => metric.kind === 'medication-adherence')?.value ?? (meds.length ? `${meds[0]!.adherence}%` : 'No medicines')}</Text><Text variant="footnote" color={colors.textSecondary}>{meds.length} active medications or reminders</Text></Card><Button title="Log a health reading" onPress={() => router.push('/quick-add/reading')} /></View> : null}
    {tab === 'Records' ? <View style={styles.sections}><SectionHeading title={`${memberRecords.length} records`} action={{ label: 'Family vault', onPress: () => router.push('/records') }} />{memberRecords.map((record) => <Card key={record.id} onPress={() => router.push(`/record/${record.id}`)}><ListRow title={record.title} subtitle={`${record.category} · ${record.date}`} leading={<IconChip size={42} background={accents[member.accent].tint}><Feather name="file-text" size={18} color={accents[member.accent].solid} /></IconChip>} /></Card>)}<Button title="Upload new record" onPress={() => router.push('/quick-add/upload')} /></View> : null}
    {tab === 'Care' ? <View style={styles.sections}><SectionHeading title="Upcoming bookings" /><BookingList bookings={memberBookings} /><SectionHeading title="Current care plan" /><Card><Text variant="headline">{member.id === 'savita' ? 'Mobility and confidence at home' : member.id === 'rajiv' ? 'Metabolic health routines' : member.id === 'neha' ? 'Energy, strength and thyroid support' : 'Sleep and active wellbeing'}</Text><Text variant="callout" color={colors.textSecondary} style={styles.gap}>A supportive plan built from current goals, tasks and care bookings.</Text></Card><SectionHeading title="Recommended professionals" />{['rhea-malhotra', 'arvind-nair', 'maya-iyer', 'kabir-sethi'].map(providerById).filter((provider) => provider?.recommendedFor.includes(member.id)).map((provider) => <Card key={provider!.id} onPress={() => router.push(`/provider/${provider!.id}`)}><ListRow title={provider!.name} subtitle={`${provider!.title} · ${provider!.matchScore}% match`} /></Card>)}<SectionHeading title="Care Captain" /><Card><ListRow title="Arjun Mehra" subtitle="Coordinates family records, tasks and care" leading={<Avatar name="Arjun Mehra" accent="blue" size={42} />} /></Card></View> : null}
  </ScreenContainer>;
}

function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text variant="overline" color={colors.textSecondary}>{label.toUpperCase()}</Text><Text variant="callout">{value}</Text></View>; }
function BookingList({ bookings }: { bookings: ReturnType<typeof useAppState>['bookings'] }) { return <View style={styles.bookingList}>{bookings.length ? bookings.map((booking) => { const provider = providerById(booking.providerId); return <Card key={booking.id} onPress={() => router.push(`/booking/${booking.id}`)}><ListRow title={provider?.name ?? booking.service} subtitle={`${booking.service} · ${booking.date}, ${booking.time}`} /></Card>; }) : <Card><Text variant="callout" color={colors.textSecondary}>No upcoming bookings.</Text></Card>}</View>; }

const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg, marginTop: spacing.lg }, profileCopy: { flex: 1, alignItems: 'flex-start', gap: spacing.xs }, updated: { textAlign: 'right', marginVertical: spacing.md }, sections: { marginTop: spacing.xxl, gap: spacing.lg }, metricRow: { flexDirection: 'row', gap: spacing.md }, metric: { flex: 1 }, gap: { marginTop: spacing.sm }, line: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border, marginVertical: spacing.lg }, info: { gap: spacing.xs }, empty: { padding: spacing.lg }, metricTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, bookingList: { gap: spacing.md } });
