import { useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { Button, Card, DetailHeader, IconChip, ListRow, ScreenContainer, Segmented, Sheet, StatusPill, Text } from '@/components';
import { family } from '@/data';
import { useAppState } from '@/state';
import { accents, colors, radius, spacing } from '@/theme';
import type { TodayItem } from '@/types';

const tabs = ['Today', 'Upcoming', 'Completed'] as const;
export default function TasksScreen() {
  const { focus } = useLocalSearchParams<{ focus?: string }>(); const { tasks, toggleTask, rescheduleTask, addTask } = useAppState(); const [tab, setTab] = useState<typeof tabs[number]>('Today'); const [member, setMember] = useState('all'); const [selected, setSelected] = useState<TodayItem | undefined>(tasks.find((item) => item.id === focus)); const [creating, setCreating] = useState(false); const [title, setTitle] = useState('');
  const filtered = tasks.filter((item) => {
    if (member !== 'all' && item.memberId !== member) return false;
    if (tab === 'Completed') return item.completed;
    if (item.completed) return false;
    return tab === 'Today' ? item.date === 'Today' : item.date !== 'Today';
  });
  return <ScreenContainer edges={['top', 'bottom']}><DetailHeader title="Family tasks" actionLabel="Create" onAction={() => setCreating(true)} /><Segmented options={tabs} value={tab} onChange={setTab} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Filter label="Everyone" active={member === 'all'} onPress={() => setMember('all')} />{family.map((item) => <Filter key={item.id} label={item.name.split(' ')[0]!} active={member === item.id} onPress={() => setMember(item.id)} />)}</ScrollView><View style={styles.list}>{filtered.length ? filtered.map((item) => <Card key={item.id} onPress={() => setSelected(item)}><ListRow title={item.title} subtitle={`${item.who} · ${item.date}, ${item.time}`} leading={<Pressable onPress={() => toggleTask(item.id)}><IconChip size={42} background={item.completed ? accents.sage.tint : accents[item.accent].tint}><Feather name={item.completed ? 'check' : item.icon} size={18} color={item.completed ? accents.sage.solid : accents[item.accent].solid} /></IconChip></Pressable>} trailing={<StatusPill label={item.completed ? 'Completed' : item.time} accent={item.completed ? 'sage' : item.accent} />} /></Card>) : <Card><Text variant="callout" color={colors.textSecondary}>No tasks in this view.</Text></Card>}</View><Button title="Create family task" onPress={() => setCreating(true)} /><Sheet visible={Boolean(selected)} onClose={() => setSelected(undefined)} title={selected?.title}><View style={styles.sheetBody}><Text variant="callout" color={colors.textSecondary}>Assigned to {selected?.who} · {selected?.date}, {selected?.time}</Text><Text variant="footnote">{selected?.note || 'No note added.'}</Text><Button title={selected?.completed ? 'Reopen task' : 'Mark complete'} onPress={() => { if (selected) toggleTask(selected.id); setSelected(undefined); }} /><Button title="Reschedule to tomorrow, 7:30 pm" variant="secondary" onPress={() => { if (selected) rescheduleTask(selected.id, '7:30 pm'); setSelected(undefined); }} /><Button title={`View ${selected?.who}’s profile`} variant="tertiary" onPress={() => { const id = selected?.memberId; setSelected(undefined); if (id) router.push(`/member/${id}`); }} /></View></Sheet><Sheet visible={creating} onClose={() => setCreating(false)} title="Create a task"><View style={styles.sheetBody}><TextInput value={title} onChangeText={setTitle} placeholder="Task title" placeholderTextColor={colors.textTertiary} style={styles.input} /><Text variant="footnote" color={colors.textSecondary}>Assigned to Arjun · Today at 7:30 pm</Text><Button title="Assign task" onPress={() => { addTask({ id: `task-${Date.now()}`, title: title || 'New family task', memberId: 'arjun', who: 'Arjun', time: '7:30 pm', date: 'Today', icon: 'check-square', accent: 'blue', completed: false }); setTitle(''); setCreating(false); }} /></View></Sheet></ScreenContainer>;
}
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.filter, active && styles.filterActive]}><Text variant="subhead" color={active ? colors.white : colors.textSecondary}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ filters: { gap: spacing.sm, paddingVertical: spacing.lg }, filter: { paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: radius.pill, backgroundColor: colors.surface }, filterActive: { backgroundColor: colors.textPrimary }, list: { gap: spacing.md, marginBottom: spacing.xxl }, sheetBody: { gap: spacing.lg }, input: { minHeight: 52, borderRadius: radius.input, backgroundColor: colors.surfaceMuted, paddingHorizontal: spacing.lg, fontSize: 16 } });
